apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: go-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-component
    app.kubernetes.io/part-of: test-app-167602486
  name: go-component
  namespace: abhindas-tenant
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: go-component
status:
  loadBalancer: {}
