apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: go-component
  namespace: abhindas-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload:abhindas-tenant-go-component
        name: container-image
        resources: {}
status: {}
