apiVersion: pipelinesascode.tekton.dev/v1alpha1
kind: Repository
metadata:
  annotations:
    appstudio.openshift.io/application: test-app-167602486
    appstudio.openshift.io/component: go-component
    build.appstudio.openshift.io/build: "true"
    build.appstudio.openshift.io/type: build
    build.appstudio.openshift.io/version: "0.1"
    pipelines.appstudio.openshift.io/type: build
  creationTimestamp: null
  name: go-component
  namespace: abhindas-tenant
spec:
  url: https://github.com/devfile-samples/devfile-sample-go-basic
